[[plugins]]
repo = 'rhysd/git-messenger.vim'
on_cmd = 'GitMessenger'
on_map = '<Plug>(git-messenger'
hook_add = '''
  nmap <silent> <C-g> <Plug>(git-messenger)

  autocmd FileType gitmessengerpopup call s:gitmessengerpopup_my_settings()
  function! s:gitmessengerpopup_my_settings() abort
    nnoremap <silent> <C-p> :<C-u>!hub openpr <cword><CR>
  endfunction
'''
