[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_source = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['deoplete.nvim']
[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
